addons:
  artifacts:
    debug: true
    paths: [libs.zip, build.zip, testbuild.zip]
    target_paths: ea3a70f2-c3bf-4b79-a79a-cc3700fbcbb5
jdk: [oraclejdk7, oraclejdk8]
language: java
script: mvn verify;./df-build.sh
# Modified by Insights Service at 2016-03-14 19:31:17.396092
