addons:
  artifacts:
    debug: true
    paths: [libs.zip, build.zip, testbuild.zip]
    target_paths: 29560cad-217d-4788-b4b6-57c0ec8cdd66
jdk: [oraclejdk7, oraclejdk8]
language: java
script: mvn verify;./df-build.sh
# Modified by Insights Service at 2016-03-13 09:03:54.272879
